### PR TITLE
Add some SSA3032X shortcuts

### PR DESCRIPTION
**Pull request by dimitarpenev**
Hello,

I have added some shortcuts for the SSA3032X.  
The SSA3032X is pretty complex so the shortcuts will become a lot pretty quickly. 
I have decided to limit myself to the most important for now. 
Additional will be added on the way. 

As I am new to Javascript there may be issues and omissions. Please take a look.

### CODE REVIEW

**Comment by mvladic** [comment]
Although `values.startFrequency !== values.startFrequency` works, I think the better way to check if number is `NaN` is `isNaN(values.startFrequency)`.

**Comment by dimitarpenev** [comment]
I have tested isNaN() few days ago and I got an issue. 
Now I have checked again and it seems working fine. 
I guess I had a different issue in the past which I have misinterpreted.
I have updated all code to use isNan()

**Comment by mvladic** [comment]
I merged this PR, but that was mistake :) because you created a new extension ZIP files but with the same name (because version is still 0.1.0) as released ZIP files thus overwriting it. 

image

Immediate consequence of this is that if someone tried to install this extensions then SHA256 check will fail. I fixed this so that I made a new release with changed SHA256 hash values. 

In the future you should first increase extension version number and then make zip files.

**Comment by dimitarpenev** [comment]
OK I will try to do it properly next time.

**Pull request merged**
